name: Pack CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  check-npm-ci-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24.18.0

      - name: Install Dependencies
        run: npm ci

      - name: Compile
        run: npm run compile
      
      - name: Pack and Vitest
        shell: bash
        run: |
          set -eo pipefail

          test_dir="$(mktemp -d)"

          tarball_name="$(npm pack)"
          mv "$tarball_name" "$test_dir"

          cp -r test "$test_dir/test"
          cat > "$test_dir/vitest.config.ts" <<EOF
          import { defineConfig } from "vitest/config"
          export default defineConfig({
            test: {
              setupFiles: "./test/setup-env.ts"
            }
          })
          EOF

          cd "$test_dir"

          npm init -y
          npm pkg set private=true
          npm pkg set type=module

          npm install "$tarball_name"
          npm install --save-dev vitest@4.1.10 
          npx vitest run